* Body Building
** Strength
** Agility
** Endurance
** Other
** Tips and Notes
*** warm up
remember to warm up your body before intense exercise

* Nutrition and Care
** Protein powder usage
*** Time and Frequency
*** Relationship with exercising and muscles

** Face and skin care
*** clean
*** hydrating/moisturize
*** anti-aging
*** current schedule
**** TODO From 2.17, Kiehl's ultra series(face creme, face cleanser, hand salve)
**** TODO From 3.3, Lab Series power wash/multi-action cleanser/age rescue face lotion
** TODO Eyes
How to reduce the visibility of the crow's feet?
** TODO Lips Hydrating
* Plan from 11.24 2015
** Endurance
*** Walk/Run as much as possible
*** Try plank to train upper limb & abdomial muscle
** Strength
Dumb bell, plank
** Agility
*** TODO Learn fighting technique
** Others 
*** practise basketball(especially ball shooting) in the morning after fly back US on Dec 1, 2015
The motivation is to transfrom my play style so that can facilitate my play
after enter 30. Another motivation is to combine the shooting practise with the upper limb
strength training. 
Suppose I pratice 20 minutes every morning and I shoot 10 balls per minute, then
I can make 200 shoots per day.

If you can find a way to practise *passing skill*, that's is even better.
 
