* Vim
** text editing notes
*** quick insert

o: insert line below
Shift+o: insert line above
*** quick delete
daw: delete word under cursor
caw: same effect + insert mode

*** undo & redo
u & Ctrl+r
*** change word 
cw
c$  : note that the "c" command would switch to insert mode
*** change errors
     To substitute new for the first old on a line type  :s/old/new
     To substitute new for all 'old's on a line type     :s/old/new/g
     To substitute phrases between two line #'s type     :#,#s/old/new/g
     To substitute all occurrences in the file type      :%s/old/new/g
     To ask for confirmation each time add 'c'           :%s/old/new/gc
*** external command
:!
      Some useful examples are:
          :!ls  or  :!dir                 -  shows a directory listing.
          :!rm  or  :!del FILENAME        -  removes file FILENAME.
*** selective write 
           ** To save part of the file, type  :#,# w FILENAME  **

  1. Once again, type  :!ls  or  :!dir  to obtain a listing of your directory
     and choose a suitable filename such as TEST.

  2. Move the cursor to the top of this lesson by pressing  *C-k*  to find the
     number of that line.  REMEMBER THIS NUMBER!

  3. Now move to the bottom of the lesson by pressing  *C-j*  to find the
     number of that line. REMEMBER THIS LINE NUMBER ALSO!

  4. To save ONLY a section to a file, type   :#,# w TEST   where #,# are
     the two numbers you remembered (top,bottom) and TEST is your filename.

  5. Again, see that the file is there with  :!ls  or  :!dir  but DO NOT
     remove it.

*** retrieve and merge file
:r FILENAME


* Emacs
** org mode
*** tables
| feature    | vim          | emacs     | comparison                     |
|------------+--------------+-----------+--------------------------------|
| navigation | extrordinary | very good | emacs+evil can approximate vim |
|            |              |           |                                |
*** fonts and notations

*bold*
/incline/
_underline_
*** org capture
** helm 
*** TODO pratice navigation via helm in emacs regularly 
* Spacemacs
** commands
*** shorthand
- S - spelling
- T - themes
- a - applications
- b - buffers
- f - files
- g - git/version control
- w - manage windows
- h - help
* Analogy & Comparison
** Quotes
*** Mastering Emacs
1) What makes /LISP/ such a fantastic language is that source code and data structures are 
intrinsically one and the same: the /LISP/ source code you read as a human is almost identical 
to how the code is manipulated as a data structure by /LISP/ ----- the distinction between the 
questions "What is data?" and "What is code?" is nil.

* Voc & Terminology 
tinkerer: a person who enjoys fixing and experimenting with machines and their parts
esoteric: confined to and understandable by only an enlightened inner circle

* Questions 
** TODO how to search a keyword in a batch of files inside emacs? 

* Problems/Projects for Pratising

** TODO study how to enter Chinese in Emacs across possible platform(Windows, Mac and Linux)
SCHEDULED: <2015-11-25 Wed>
Also need to figure out what *encoding* format to use. Unicode-8 or Unicode-16
or else?  

If I figure out this, then from 2016, I'll keep my daily notes in Emacs instead of Lyx.
