* Writing Projects
** math
*** probability learning series 
*** optimization learning series
** stat 
*** high dimension stat learning series
*** ESL book notes
** Machine Learning
*** machine learning general notes file
** programming
*** sicp and function programming learning series
*** python and R programming
* Oral Expression
** small habits
*** TODO recite a nice paragraph
    SCHEDULED: <2017-07-21 Fri +1w>
    :PROPERTIES:
    :LAST_REPEAT: [2017-09-27 Wed 18:08]
    :END:
    - State "DONE"       from "TODO"       [2017-09-27 Wed 18:08]
    - State "DONE"       from "TODO"       [2017-09-27 Wed 18:08]
    - State "DONE"       from "TODO"       [2017-09-27 Wed 18:08]
*** TODO call grandparents
SCHEDULED: <2017-07-30 Sun +1m>
:PROPERTIES:
:LAST_REPEAT: [2017-09-27 Wed 18:08]
:END:
- State "DONE"       from "TODO"       [2017-09-27 Wed 18:08]
* Voc
** before 2017 Oct
cortical: of or relating to a cortex
cortex: the tissue forming the outer layer of an organ or structure in plant or animal;
        the layer of unmyelinated neurons (the grey matter) forming the cortex of the cerebrum 
phenotype: what an organism looks like as a consequence of the interaction of its genotype and the environment
pedigree: the descendants of one individual;
          line of descent of a purebred animal
 
 harbinger: A harbinger is something that comes before and that shows what will follow in the future. The robin is a harbinger of spring––its presence means spring is coming soon.
 shun: avoid and stay away from deliberately; stay clear of

 *glimer of hope*
 brethren: The Bible often uses the word brethren to indicate brothers. It is a fancy plural form of "brother" most often used formally when speaking in a religious tone.

*hung one's head* : this is an idiom which has the following meaning

Hang one's head: let it fall forward (e.g., when ashamed); a downward droop or bend
eg.
After the teacher caught me cheating, I hung my head in shame.
Athletes caught taking drugs should hang their heads in shame.

When a person commits suicide or is executed by hanging, we use hang/hanged. "Hung" is never used in such cases. e.g.,
eg.
He was hanged for murder. (executed)
He said he would hang himself. (suicide)


revenant: gui lai zhe

Pegasus: 天馬座

discern: perceive, recognize

verbatim: 逐字翻译

myriad: 无数的; 多种的，各式各样的

discretionary: 任意的; 自由决定的; 酌情行事的; 便宜行事的

*idiosyncratic*: 乖僻的; 怪异的

plethora: 过多，过剩

impediment: 妨碍，阻止; 口吃，结巴; 障碍物

laminate: vt.（将薄片砌合在一起）制成（材料）； 将（金属）锻压成薄片； n.层压材料； 叠层，层压；

relegate: dismiss to an inferior rank or position

hereditary:of or relating to inheritance
** 2017 
masochism/mæsəkɪzəm/ : 受虐狂； 被虐待狂； 自虐
gimmick: a trick or device intended to attract attention, publicity, or business
** 2018
   spank 掴
   juggle

   step into one's shoe
   jockey 驾驶，操作； 欺骗，欺诈； 骑马，驾驭

   susceptible: likely or liable to be influenced or harmed by a particular thing, *synonyms*: open to · receptive to · vulnerable to · defenseless against

   feint: a deceptive or pretended blow, thrust, or other movement, especially in boxing or fencing

   meaty: 1. fleshy; brawny
          2. full of substance or interest; satisfying
   
   tantamount: equivalent in seriousness to; virtually the same as

   recalibrate 
   
   tenacity: the quality or fact of being able to grip something firmly; grip
   synonyms:  persistence · pertinacity · determination · perseverance · doggedness · tenaciousness
