* Daily accumaltion
** prepare and recheck the required document for *a thing* carefully, don't waste time on those potential missing items
*** eg: 2017-7-14, forgot I-94 and change of address confirmation when renewing driver's license
** After a heavy snow, remove the snow on the car immediately. Don't wait till tomorrow.
** You can learn a lot of things when eating, even meditation!
** Be water, my friend.
** If you have questions or doubts when you speak to a person, ask them out as soon as you realized
*** 8.15 costco
I was try to buy a hot dog which is 1.5, but the clerk thought it was
chicken cake so she charged it for 2.99. I realzed as soon as she gave
me the receipt but fail to brought it up!
** Don't rely too much on a checklist you made yourself

Example: Forget to bring Dongdong the shell I collect in the Nov 2015 back try.
Try to think outside of the box and see whether you forget to include some thing important
** how to improve the analytical skills
From Quora:
"I would say instead: *make things*.

Solving puzzles is easy. Try and make a puzzle. Make one that's difficult to
solve. Make one that's easy to solve. You like flash puzzle games? (I like flash
puzzle games). Design one with a learning curve. Design one with knacks and
bottlenecks, so that you can solve it easily if you've got the trick but take a
long time to figure out the trick. But make it solvable by somebody who doesn't
need to read your mind to figure it out.

(pause)

Now mess yourself up. Do two things at once. Try to play some music. Fingering
chords and picking notes is easy. Try to write some good music. Or really,
singing and playing music is difficult enough. Try to do it discordantly. Play
and sing in canon. Now dance while doing it.

Einstein once described how a person only really understood something if he
could explain it to his grandmother. I think if you really can solve puzzles and
analyse things, you can create problems that will teach people how to analyse
things properly. Solving problems is easy; making problems is hard. You try to
write a fifth-grade math paper, keeping the level low enough while still being
difficult.

I also believe difficulty of analysis rises with depth and complexity. Doing two
things at once is difficult and will stretch the plasticity of your brain. I'm
eager to try chess-boxing, simply because it is going to be extremely difficult
to mode-shift from a physical game to a mental one. Already when I hit the
punching bag it's difficult to remember routines and how to punch effectively;
imagine recalling the Queen's Gambit Refused."
* Dressing
** How to pack a suite? How a fold the suite?
** shirt size
14 1/2, 32-33
** pant size
with a belt, 32-30 is good
** prepare more shirts and pants for work requirement
** how to keep your clothes clean? how to wash some special ones(shirts, suites, formal pants)?
