* Reading Notes
** Music
*** pitched accent
Pitch accent is a feature of certain languages whereby variations in pitch
(linguistic tones) can be used to differentiate words, but where the potentially
distinctive tones are restricted to only one or two syllables within a word – as
opposed to fully tonal languages like Standard Chinese, where each syllable can
have an independent tone. In a pitch accent language, the syllable with phonemic
tone is typically one that is acoustically prominent (stressed). Also many words
may not be marked for tone at all.
*** tonal language
Tone is the use of pitch in language to distinguish lexical or grammatical
meaning – that is, to distinguish or to inflect words.[1] All verbal languages
use pitch to express emotional and other paralinguistic information and to
convey emphasis, contrast, and other such features in what is called intonation,
but not all languages use tones to distinguish words or their inflections,
analogously to consonants and vowels. Languages that do have this feature are
called tonal languages.
