*  Filing As A Resident Alien
If you have determined that you are a resident alien for tax purposes,
the following information applies to you.

1) you will file Form 1040, 1040EZ, or 1040A
2) you are not required to file Form 8843
3) you must declare your worldwide income, not just your U.S. earned income
4) your bank interest is considered taxable income
5) Social Security taxes (FICA including Medicare) should be withheld from your wages
5) Some resident tax filers may still qualify for treaty benefits if
   the maximum presence limitation has not been met for that
   particular tax treaty benefit (refer to IRS Publication 901) ‐ you
   will need to complete Form 8833 and submit it along with your 1040.

6) If you are claiming a tax treaty benefit as a resident alien for tax purposes, mail your return to:
Department of the Treasury, Internal Revenue Service, Austin, TX 73301-0215.

** Verification for treaty exemption
 You will not be an exempt individual as a student in 2014 if you have
 been exempt as a teacher, trainee, or student for any part of more
 than 5 calendar years unless you meet *both* of the following
 requirements.

1) You establish that you do not intend to reside permanently in the United States.

2) You have substantially complied with the requirements of your visa.
