* Library hours Sep 13 - Dec 10
** LSM & Kilmer
8 am - 2 am Mon - Thur
     - Midnight Fri
10 am - Midnight Sat
Noon - 2 am Sunday
* tennis notes
** how to measure grip size?
** five fingers
thumb, index, middle, ring, little
** how to hit the ball with the racquet in the right way with good strength
** movement pace
* question: how to think about the recent CCTV plagiarism on Wang Yuanzong's photos
** compare this with Richard Stallman's free software campaign
* DONE reorganize Xiaochuan Liu's math intro lecture notes
  CLOSED: [2015-09-18 Fri 17:16]
Finished organizing notes of analysis 1&2, linear algebra, knot theory, combinatorics intro
and graph theory & probalistic combinatorics.
for knot theory, missing the book references and the 1st month problem set
* Misc
** DONE bring new CPT for Courtney
   CLOSED: [2015-09-09 Wed 16:31] SCHEDULED: <2015-09-08 Tue>
** DONE meet student Liya Guan
   CLOSED: [2015-09-11 Fri 14:26] SCHEDULED: <2015-09-11 Fri>
** DONE register fall GA insurance
   CLOSED: [2015-09-29 Tue 17:31] SCHEDULED: <2015-09-11 Fri>
** TODO do some study about car tires
what tires are suitable for my car?
** DONE find out what's behind the sound with the tire rotation
   CLOSED: [2015-09-18 Fri 10:39] SCHEDULED: <2015-09-23 Wed>
if necessary, change the tires
also, change the engine oil if necessary
*** turns out tire rotation solve the problem
** DONE buy desk lamp bulbs
   CLOSED: [2015-09-30 Wed 15:03] SCHEDULED: <2015-09-22 Tue>
bought an LED

** rutgers algorithm course
*** leftist tree
Leftist trees are advantageous because of their ability to merge
quickly, compared to binary heaps which take O(n). In almost all
cases, the merging of skew heaps has better performance. However
merging leftist heaps has worst-case O(log n) complexity while merging
skew heaps has only amortized O(log n) complexity.
*** amortizing analysis
*** priority queue
*** binary heap
