* Trigometric Series
** partial sum of $\sin{k}$ is bounded, while for $\sin{k^2}$ it is not
 For the first series, note that
\[
2\sin{k}\sin{0.5}=\cos(k - 0.5) \minus \cos(k + 0.5).
\].
But this trick does't work since $k^2$ is  not a arithmetic progression.
*** Tao's answer on the second part
No. If one selects a number k at random from 1 to a large number n,
then for any fixed h, the random variables sin((k+1)2),…,sin((k+h)2)
asymptotically have mean zero, variance 1/2, and covariances 0, from
standard Weyl sum estimates. Hence the variance of ∑hi=1sin((k+i)2) is
asymptotically h/2, which goes to infinity as h→∞. On the other hand,
if the partial sums of sin(k2) were bounded, then this variance would
have to be bounded also. [Exercise: what part of the above argument
breaks down when working with sin(k) instead of sin(k2)?]

It may be possible to push this argument to show that the partial sums
have to fluctuate by ≫n√ infinitely often, but I haven't checked this
(certainly a lower bound of ≫nε for some small ε>0 should be possible
from the above argument, perhaps contingent on some conjecture about
the irrationality measure of π). Heuristically, the law of the
iterated logarithm suggests that the sum can occasionally get as large
as ≫nloglogn−−−−−−−−√, but no larger.
